local:
  database-url: jdbc:mysql://localhost:3306/dvc_db
  database-user: root
  database-password: minhtranquang2197

deploy:
  database-url: jdbc:mysql://ofcmikjy9x4lroa2.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/orvki1avp7xkboe1?user=qnq5wofuq6zieuvn
  database-user: qnq5wofuq6zieuvn
  database-password: jwguy5jaovydz10h

spring:
  application:
    name: dvc_barber_service
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${deploy.database-url}
    username: ${deploy.database-user}
    password: ${deploy.database-password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql:
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        security: debug

app:
  cache:
    expire-time: 15
  access-token:
    expire-time: 15
    secret-key: ftoLRVxHq82BzLq3stXhnOJRo4azrVab
  refresh-token:
    expire-time: 4320