local:
  database-url: jdbc:mysql://localhost:3306/dvc_db
  database-user: root
  database-password: minhtranquang2197

spring:
  application:
    name: dvc_barber_service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${local.database-url}
    username: ${local.database-user}
    password: ${local.database-password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: