spring:
  application:
    name: dvc_barber_service
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/dvc_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:minhtranquang2197}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql:
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        security: debug

app:
  cache:
    expire-time: 15
  access-token:
    expire-time: 15
    secret-key: ftoLRVxHq82BzLq3stXhnOJRo4azrVab
  refresh-token:
    expire-time: 4320
  default-password: 1234567
  init-account:
    first-name: Đại Việt
    last-name: Cát
    phone: 0123456789
  domain:
    goong:
      host: ${GOONG_HOST:https://rsapi.goong.io}
      places: ${GOONG_PLACES:/Place/AutoComplete}
      place-detail: ${GOONG_PLACE_DETAIL:/geocode}
  key:
    goong: ${GOONG_API_KEY:PosiudHQxV2Yx5Zt5f2tbuqy1XlTUAJ3aym7tcLq}

